<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="game" nsURI="http://www.esolution.com/connect4" nsPrefix="connect4">
  <eClassifiers xsi:type="ecore:EClass" name="Game"/>
  <eClassifiers xsi:type="ecore:EClass" name="Team"/>
  <eClassifiers xsi:type="ecore:EClass" name="Board">
    <eStructuralFeatures xsi:type="ecore:EReference" name="square" upperBound="-1"
        eType="#//Square" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Piece" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RedPiece" eSuperTypes="#//Piece"/>
  <eClassifiers xsi:type="ecore:EClass" name="YellowPiece" eSuperTypes="#//Piece"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Side">
    <eLiterals name="YELLOW"/>
    <eLiterals name="RED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Square"/>
  <eClassifiers xsi:type="ecore:EClass" name="Player" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="HumanPlayer" eSuperTypes="#//Player"/>
  <eClassifiers xsi:type="ecore:EClass" name="RandomPlayer" eSuperTypes="#//Player"/>
  <eClassifiers xsi:type="ecore:EClass" name="AIPlayer" eSuperTypes="#//Player"/>
</ecore:EPackage>
