<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="game" nsURI="http://www.esolution.com/connect4" nsPrefix="connect4">
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EReference" name="board" lowerBound="1" eType="#//Board"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teams" upperBound="2" eType="#//Team"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Team">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="side" eType="#//Side"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="1"
        eType="#//Player" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Board">
    <eOperations name="getFirstAvailableSquare" eType="#//Square">
      <eParameters name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="squares" upperBound="-1"
        eType="#//Square" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbRow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="6"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token" abstract="true" interface="true">
    <eOperations name="getSide" eType="#//Side"/>
    <eOperations name="getOppositeSide" eType="#//Side"/>
    <eOperations name="getImageFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="square" lowerBound="1"
        eType="#//Square" eOpposite="#//Square/token"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RedToken" eSuperTypes="#//Token"/>
  <eClassifiers xsi:type="ecore:EClass" name="YellowToken" eSuperTypes="#//Token"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Side">
    <eLiterals name="YELLOW"/>
    <eLiterals name="RED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Square">
    <eOperations name="getImage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eOperations name="isEmpty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="token" eType="#//Token"
        eOpposite="#//Token/square"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokens" upperBound="21"
        eType="#//Token" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HumanPlayer" eSuperTypes="#//Player"/>
  <eClassifiers xsi:type="ecore:EClass" name="RandomPlayer" eSuperTypes="#//Player"/>
  <eClassifiers xsi:type="ecore:EClass" name="AIPlayer" eSuperTypes="#//Player"/>
</ecore:EPackage>
